version: '3.8'

services:
  api:
    build:
      context: ./BackEnd
      dockerfile: TSM.API/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=TechnicalStackManagement;User=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True
    depends_on:
      - db
    networks:
      - tsm-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - tsm-network

networks:
  tsm-network:
    driver: bridge

volumes:
  sqlserver-data: 